services:
  - type: web
    name: news-backend
    env: node
    plan: free
    branch: develop
    rootDir: Backend # вказуємо директорію з файлом server.js Backend
    buildCommand: ""
    startCommand: "npm start" # запускаємо server.js
    autoDeploy: true
